services: 
  identity:
    image: quay.io/keycloak/keycloak:26.4.2 
    command: [ 'start-dev' ] 
    environment: 
      - KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD
      - KC_DB
      - KC_DB_URL
      - KC_DB_USERNAME
      - KC_PROXY
      - KC_DB_PASSWORD
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT}" 
    networks: 
      - smart-task-hub-network 
    depends_on: 
      - postgres 
  postgres: 
    image: postgres:18.0-alpine3.22 
    restart: always 
    hostname: ${POSTGRES_HOST} 
    ports: 
      - "${POSTGRES_PORT}:${POSTGRES_PORT}" 
    environment: 
      - POSTGRES_USER 
      - POSTGRES_PASSWORD 
    volumes: 
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    networks: 
      - smart-task-hub-network 
    
networks:
  smart-task-hub-network: 
    driver: bridge

volumes: 
  postgres: