name: Frontend Development Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      # 1. Checkout & Setup
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # 2. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 3. Code Quality Checks (Lint, Prettier, Type-check)
      - name: Run Code Quality Checks
        run: |
          npm run lint || true
          npm run format:check || true
          npx tsc --noEmit || true

      # 4. Run Tests
      - name: Run Unit Tests & Coverage
        run: |
          npm run test:run
          npm run test:coverage

      # 5. Build & Deploy
      - name: Build & Deploy
        run: |
          npm run build
        #   npx vercel --prod --yes --token=${{ secrets.TRELLO_FRONTEND_VERCEL_TOKEN }}
        # env:
        #   VERCEL_ORG_ID: ${{ vars.TRELLO_FRONTEND_VERCEL_ORG_ID }}
        #   VERCEL_PROJECT_ID: ${{ vars.TRELLO_FRONTEND_VERCEL_PROJECT_ID }}
        #   VITE_TRELLO_LIKE_API_URL: ${{ vars.VITE_TRELLO_LIKE_API_URL }}

      # 7. Login ghcr.io
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # 8. build docker image
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/nashtech-garage/smart-taskhub-fe:latest

      # 9. Scan docker image with trivy
      - name: "Scan Docker Image with Trivy"
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/nashtech-garage/smart-taskhub-fe:latest'
          format: 'sarif'
          scan-type: 'image'
          severity: 'CRITICAL,HIGH,WARNING'
          output: 'trivy-results.sarif'
      
      # 10. Push Trivy scan results to github Security tab
      - name: "Upload Trivy scan results to GitHub Security tab"
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          category: 'image'
